- db/seeds.rb
Added some task on the BLM cause in the seedfile
> added task to seedfile

- app/controllers/pages_controller.rb
- app/controllers/users_controller.rb
- app/views/layouts/application.html.erb
- app/views/users/create.html.erb
- app/views/users/new.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- test/controllers/actions_controller_test.rb
1. Added user controller with 3 empty methods
2. added views.erb files with corresponding pages to the above
> user controller and views completed

- app/assets/stylesheets/pages/_home.scss
- app/javascript/packs/_navbar.js
- app/views/pages/home.html.erb
added basic HTML structure to our home page with CSS placeholders
> added skeleton structure of home page.

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_causes.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_index.scss
- app/javascript/packs/_navbar.js
- app/views/causes/index.html.erb
- app/views/pages/home.html.erb
Another static HTML & CSS skeleton, this time for the select-a-cause page
> Select cause

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_causes.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_show.scss
- app/javascript/packs/_navbar.js
- app/views/causes/index.html.erb
- app/views/causes/show.html.erb
- app/views/pages/home.html.erb
Added another skeleton HTML & CSS for the cause page. This is a dumb page in that it doesn't link anywhere, but it will be easier to code the links to buttons that already exist :)
> Cause page

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_causes.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_show.scss
- app/javascript/packs/_navbar.js
- app/views/causes/index.html.erb
- app/views/causes/show.html.erb
- app/views/pages/home.html.erb
Hi Annie. 
When I removed the Inspector I noticed a couple of divs were right-aligned on the cause page (theoa.org/causes). I've centered them now.
> Centering divs

- app/models/cause.rb
- app/models/task.rb
- config/environments/development.rb
- config/storage.yml
- db/migrate/20210603120951_create_active_storage_tables.active_storage.rb
- db/schema.rb
- db/seeds.rb
also added require "open-uri" to cause1 in seed file so it can be copied to other causes once we have decided on images.
> added Active Record support for Cloudinary

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
links added to home page for
1. logo > home 
2. take action > causes
3. login > login page
> added links for logo and on screen buttons

- app/controllers/causes_controller.rb
- app/controllers/users_controller.rb
- app/views/causes/_task_list.html.erb
- app/views/causes/index.html.erb
- db/migrate/20210603205914_remove_url_from_tasks.rb
- db/migrate/20210603210122_add_url_to_tasks.rb
- db/schema.rb
- db/seeds.rb
Still doing something with the url but it opens in a new window and is linked in the task.name!
> Checkboxes

- app/controllers/causes_controller.rb
> fixed the .env file

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_newsfeed.scss
- app/assets/stylesheets/pages/_cause_task_show.scss
- app/views/causes/cause_task_show.html.erb
Added some styling on the pull container
> added some simple styling

- app/controllers/causes_controller.rb
- app/views/causes/cause_task_show.html.erb
- db/migrate/20210612151621_add_twitter_to_causes.rb
- db/migrate/20210612152445_add_photo_url_to_causes.rb
- db/schema.rb
- db/seeds.rb
Added the twitter photo and URL to the causes database in the seed file
> Twitter handler db

- db/seeds.rb
> fixed error on seaspearacy

- app/assets/stylesheets/pages/_home.scss
- app/controllers/causes_controller.rb
- app/views/pages/home.html.erb
As above. Updated font awesome icons on home page. 
For now these are centred above each 'box', but they can be moved.
The icons are also just ones I grabbed quickly from FA. Updating these is easy.
> updated fontawesome icons on front page

- app/controllers/causes_controller.rb
- db/seeds.rb
> fixed seed file

- app/assets/stylesheets/components/_footer.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
need to sort out why footer overlays on cause index page and on signup/login page
> footer fix

- app/assets/stylesheets/pages/_home.scss
Super simple. Moved text down as shown.
> moved homepage welcome text down

- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/causes/cause_task_show.html.erb
- app/views/devise/registrations/new.html.erb
Updated sign up page. 
1. Removed placeholders.
2. Centered everything.
3. Added background 'do your part' image so it's not just a blank page.
4. Removed footer from this page only.
> updated sign up page

- app/assets/stylesheets/pages/_cause_task_show.scss
- app/controllers/causes_controller.rb
- app/views/causes/cause_task_show.html.erb
Updated.
1. I was a div layout from one of the other merges wreaking havoc on the page. 
2. Updated causes_controller with 30 tweets instead of 2. 
3. Updated _scss file to remove border on more-info-show box at the bottom. 
Resolved.
> updated cause task page, working

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/pages/_home.scss
1. Readded footer. 
2. Kept height of sign-up container at 100vh so you don't see the footer unless you scroll down. Just a cleaner look. 
3. Also made home page background #f6f6f6 rather than white. 
4. Carousel images resized due to footer now being back on the home page.
> re-added footer

- db/seeds.rb
I've added further tasks into the seed file, there are now several tasks for each relevant cause.
> added further tasks to seed file

- app/assets/stylesheets/components/_background.scss
- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/pages/_causes.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/causes/index.html.erb
Widened cause boxes to 80% of page width rather than 65%.
> widened causes index

- app/controllers/users_controller.rb
- app/views/users/_show.html.erb
- app/views/users/dashboard.html.erb
part 1 - displaying a user's completed task count out of all possible tasks for the cause on the page.
part 2 - TO DO - change the path on the btn to completed more tasks
> Logic dashboard tasks

- app/assets/stylesheets/pages/_causes.scss
- app/views/causes/index.html.erb
> fixed the button in the center of the screen

- app/assets/stylesheets/components/_footer.scss
- app/views/shared/_footer.html.erb
> add center info to not have blank space in footer

- app/assets/stylesheets/pages/_cause_task_show.scss
- app/views/causes/cause_task_show.html.erb
1. Tidied up the "more info" and "notable organisations" section of cause task show page.
2. Added links for the notable organisations URLs.
> added links and tidied up causes task page

- app/views/causes/cause_task_show.html.erb
- app/views/users/dashboard.html.erb
So these arrows now match the homepage arrows. However, did we want to remove the button style or leave it? Also need to increase size once I know which way we are going
> changed arrow to match style on homepage

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_dashboard.scss
- app/assets/stylesheets/pages/_cause_task_show.scss
- app/views/users/_show.html.erb
- app/views/users/dashboard.html.erb
- db/seeds.rb
Finally managed to get this working without it tripping over itself. 
1. Added carousel buttons like the home page (no hover effect such as cursor: pointer yet)
2. Community box added on the left. As discussed w/ Annie, the top two boxes update as you tick off tasks.
3. User box added to the right. The middle section is a scrollable list of completed tasks. These are in twos as it's only pulling the name of the task, not it's longer description. 
4. Managed to sort out green ticks for completed tasks. It looked neater in the body rather than the head of the box. 
5. I replaced the huge add more button with a '+' symbol attached to the bottom right hand corner of the user box. 
6. The change to the seed file was just adding the 'g' to jpg on BLM. 
Still to do:
1. Logic for the points …
> 90% updated dashboard

- app/assets/stylesheets/pages/_cause_task_show.scss
Updated as per your suggestion Annie in previous PR.
Put an object-fit: cover; on the images within the carousel, and padding-top: 25px; on it's container. See below.
https://user-images.githubusercontent.com/76408528/122918258-d8084180-d356-11eb-8d8f-5b5104739f24.png
https://user-images.githubusercontent.com/76408528/122918167-bdce6380-d356-11eb-83ed-fcfe3c6b6696.png
https://user-images.githubusercontent.com/76408528/122918212-cb83e900-d356-11eb-9842-5165faa61a7d.png
> Fixed carousel buttons

- app/assets/stylesheets/pages/_causes.scss
- app/javascript/causes.js
- app/views/causes/index.html.erb
You can now select a specific time. 
problem : you can select 5 & 10 minutes at the same time:
> 50% of the javascript done but working for demo

- app/assets/stylesheets/pages/_home.scss
Quickly edited button to match the others on the page
> edited letsgo button

- app/views/causes/_task_list.html.erb
Added the point for each task in the checklist
> Added the task.point in the checklist

- app/javascript/causes.js
The javascript is now working and you can only select one time
> working now you can only select one time

- db/seeds.rb
I've added some more tasks to the seed file to bulk it out. Will add more over next few days
> added more tasks to seed file

- app/assets/stylesheets/pages/_cause_task_show.scss
- app/views/causes/cause_task_show.html.erb
As shown in the OA, moved the notable orgs and more info next to carousel. To keep "DO YOUR PART' I've moved the boxes to the bottom of the carousel image and moved the background image up a bit. 
I think if we try and merge this with the CSS style you showed Annie, it would be a good mix.
> moved more info and orgs boxes to top of page

- app/assets/stylesheets/pages/_cause_task_show.scss
- app/views/causes/cause_task_show.html.erb
Reverts neilgoodridge/the-oa#113
> Revert "moved more info and orgs boxes to top of page"

- app/assets/stylesheets/pages/_cause_task_show.scss
- app/views/causes/cause_task_show.html.erb
For the third time of asking, here we go
> put divs back and rewrote some css

- app/assets/stylesheets/components/_dashboard.scss
- app/views/users/_show.html.erb
- app/views/users/dashboard.html.erb
Moved the plus so it's in the correct place. Quite a straightforward move. 
I did move the div container from dashboard to show though to make it easier to position.
> moved + button on dashboard

- public/500.html
> added 505 page too

- app/controllers/causes_controller.rb
- app/views/users/dashboard.html.erb
breaks on next cause index 3 - need to ticket it
> changed previous and next methods

- app/views/users/dashboard.html.erb
> added a background in the dashboard view

- app/assets/stylesheets/components/_dashboard.scss
- db/seeds.rb
1. I have added tasks for each relevant cause for our presentation, with links attached.
2. I have also made alterations to the below, so that the "your progress" section of the dashboard is bigger:
_dashboard.scss: 
.progress-info: height
.keepup: padding-top
However this depends how it is meant to be presented - feel free to make changes to this appropriately so that the display fits best
> final upload to seed file and css alterations

- app/assets/stylesheets/components/_background.scss
- app/assets/stylesheets/pages/_causes.scss
- app/views/causes/index.html.erb
Cause index updated too. This needed some serious resizing to fit it all on one page. All there though. Screenshots at 100% in Chrome.
> resized cause_index page

- app/assets/stylesheets/components/_dashboard.scss
- app/views/users/dashboard.html.erb
Dashboard done too. There are a couple of bits I'm struggling to space without it affecting other pages and some spacing around some of the text, but here it is right now. 98% done. 
I've also updated all pages I've committed to Quicksand font. 
Thoughts on 'your progress' being topped by the same blue as the progress boxes and '+' sign. I did this just to separate it from the completed tasks (green) a bit. Easily reversible if not.
> resized dashboard

- app/assets/stylesheets/pages/_home.scss
Homepage font updated in how it works. Checked in Chrome at 100%.
> updated How it workds font to font-family: 'Quicksand', sans-serif;

- app/assets/stylesheets/pages/_cause_task_show.scss
- app/views/causes/_task_list.html.erb
Capitalised and increased font size
> capitalised Save
